#!/bin/bash

MANTIS_URL="https://mantis.xmachina.de/view.php?id="

ticket_no=$1
if [[ $1 -eq 0 ]] ; then
	while read pipe; do
		ticket_no=$pipe	
	done
fi
echo "Opening Mantis-Ticket: $ticket_no"
ticket_url=$MANTIS_URL$ticket_no
echo "Destination: $ticket_url"
xdg-open $ticket_url
